refactor: move export android to export project

diff --git a/.github/actions/build-godot/action.yml b/.github/actions/build-godot/action.yml
--- a/.github/actions/build-godot/action.yml
+++ b/.github/actions/build-godot/action.yml
@@ -20,23 +20,34 @@ inputs:
   artifact:
     description: Desired name for the uploaded NuGet package artifact.
     required: true
-  keystore:
-    description: Desired name for the uploaded NuGet package artifact.
-    required: true
-  keystore-user:
-    description: Desired name for the uploaded NuGet package artifact.
-    required: true
-  keystore-password:
-    description: Desired name for the uploaded NuGet package artifact.
-    required: true
   duration:
     description: Retention duration (in days) for the uploaded artifact. A value of 0 uses the default retention period.
     required: false
     default: "1"
+  android-keystore:
+    description: Base64-encoded Android keystore.
+    required: false
+    default: ""
+  android-keystore-user:
+    description: Keystore username for Android export.
+    required: false
+    default: ""
+  android-keystore-password:
+    description: Keystore password for Android export.
+    required: false
+    default: ""
 
 runs:
   using: composite
   steps:
+    - name: 📖 Get Godot Version
+      id: get_godot_version
+      shell: bash
+      run: |
+        chmod +x "${{ github.action_path }}/scripts/get_godot_version.sh"
+        godot_version=$("${{ github.action_path }}/scripts/get_godot_version.sh" "${{ inputs.global-json-file }}")
+        echo godot_version="$godot_version" >> "$GITHUB_OUTPUT"
+
     - name: 📂 Get Templates Directory
       id: get_templates_dir
       if: inputs.platform == 'Android'
@@ -45,14 +56,6 @@ runs:
         chmod +x "${{ github.action_path }}/scripts/get_templates_dir.sh"
         templates_dir=$("${{ github.action_path }}/scripts/get_templates_dir.sh" "${{ runner.os }}")
         echo templates_dir=${templates_dir} >> "$GITHUB_OUTPUT"
-
-    - name: 📖 Get Godot Version
-      id: get_godot_version
-      shell: bash
-      run: |
-        chmod +x "${{ github.action_path }}/scripts/get_godot_version.sh"
-        godot_version=$("${{ github.action_path }}/scripts/get_godot_version.sh" "${{ inputs.global-json-file }}")
-        echo godot_version="$godot_version" >> "$GITHUB_OUTPUT"
 
     - name: 📂 Install Android Template
       if: inputs.platform == 'Android'
@@ -70,54 +73,26 @@ runs:
         echo export_options=${export_options} >> "$GITHUB_OUTPUT"
 
     - name: 📂 Export Project
+      id: export_project
       shell: bash
       run: |
-        # Ensure the artifacts directory exists
-        if ! mkdir -p ~/.artifacts; then
-          echo "Error: Failed to create directory ~/.artifacts."
-          exit 1
+        if ! mkdir -p ${artifacts_dir}; then
+           echo "Error: Failed to create directory ${artifacts_dir}."
+           exit 1
         fi
 
-        echo "Artifacts directory contents:"
-        ls -la ~/.artifacts
+        case "${{ inputs.platform }}" in
+          "Android")
+            chmod +x "${{ github.action_path }}/scripts/export_android_project.sh"
+            file=$("${{ github.action_path }}/scripts/export_android_project.sh" "${{ inputs.project }}" "${{ inputs.preset }}" "${{ inputs.artifact }}" "${{ inputs.android-keystore }}" "${{ inputs.android-keystore-user }}" "${{ inputs.android-keystore-password }}")
+            ;;
+          "iOS")
+            echo "Exporting for iOS platform..."
+            ;;
+          *)
+            echo "Error: Unsupported platform ${{ inputs.platform }}"
 
-        # Ensure the Android directory exists
-        if ! mkdir -p ~/.android; then
-          echo "Error: Failed to create directory ~/.android."
-          exit 1
-        fi
-
-        if ! echo -n "${{ inputs.keystore }}" | base64 -d > ~/.android/release.keystore; then
-          echo "Error: Failed to decode and save the Android keystore."
-          exit 1
-        fi
-
-        echo "Android directory contents after saving keystore:"
-        ls -la ~/.android
-
-        keytool -list -keystore ~/.android/release.keystore -storepass ${{ inputs.keystore-password }}
-
-        if [ $? -eq 0 ]; then
-          echo "Keystore file is valid."
-        else
-          echo "Error: Keystore file is invalid or cannot be accessed."
-          exit 1
-        fi
-
-        export GODOT_ANDROID_KEYSTORE_RELEASE_PATH=~/.android/release.keystore
-        export GODOT_ANDROID_KEYSTORE_RELEASE_USER=${{ inputs.keystore-user }}
-        export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=${{ inputs.keystore-password }}
-
-        echo "Environment variables:"
-        env | grep GODOT_ANDROID_KEYSTORE
-
-        # Run the Godot export command
-        if ! godot --path "${{ inputs.project }}" --headless --export-release "${{ inputs.preset }}" ~/.artifacts/${{ inputs.artifact }}.apk; then
-          echo "Error: Godot export failed."
-          exit 1
-        fi
-
-        echo "Export completed successfully. Artifact is located in ~/.artifacts."
+          echo file=${file} >> "$GITHUB_OUTPUT"
 
     - name: 📤 Upload Android Artifact
       uses: actions/upload-artifact@v4
