Update godot-pack.yml

diff --git a/.github/workflows/godot-pack.yml b/.github/workflows/godot-pack.yml
--- a/.github/workflows/godot-pack.yml
+++ b/.github/workflows/godot-pack.yml
@@ -26,7 +26,12 @@ jobs:
 
       - name: 🔗 Set Dynamic Paths
         run: |
-          ARTIFACT_NAME=$(echo "${{ inputs.id }}" | sed -E 's/([a-z])([A-Z])/\1-\2/g' | tr '[:upper:]' '[:lower:]')-${{ inputs.version }}-godot-addon
+          if [ -z "${{ inputs.id }}" ] || [ -z "${{ inputs.version }}" ]; then
+            echo "Error: inputs.id or inputs.version is not set."
+            exit 1
+          fi
+          
+          ARTIFACT_NAME="$(echo "${{ inputs.id }}" | sed -E 's/([a-z])([A-Z])/\1-\2/g' | tr '[:upper:]' '[:lower:]')-${{ inputs.version }}-godot-addon"
           echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
           echo "ARTIFACT=$ARTIFACT_DIR/$ARTIFACT_NAME" >> $GITHUB_ENV
 
